---
# file: .travis.yml

language: python

python:
  - "3.6"
  - "3.7"

env:
  matrix:
    - MOLECULE_DIST: 'jam82/arch-molecule:latest'
    - MOLECULE_DIST: 'jam82/centos-molecule:7'
    - MOLECULE_DIST: 'jam82/ubuntu-molecule:18.04'

services: docker

install:
  - pip install ansible-lint docker flake8 molecule testinfra yamllint

script:
  - molecule --version
  - ansible --version
  - molecule test
